services:
  api:
    build: .
    container_name: gestor_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: gestor_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
     - pgdata:/var/lib/postgresql/data
     - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: